name: UT Digital Antiquity
markdown: kramdown
theme: jekyll-theme-cayman
defaults:
  - scope:
      path: ""          # empty = site root and below
      type: "pages"     # applies to regular pages (not posts)
    values:
      layout: page
